import { Button, VerticalBox } from "std-widgets.slint";





export component AppWindow inherits Window {
    title: "Remote Play Non Steam Games";
    icon: @image_url("../assets/icon.png");

    callback test_function() -> string;

    VerticalLayout {

    
    test_label := Text {
        text: "sigma";
    }


    Button {
        text: "Example button";
        clicked => {
            test_label.text = root.test_function();
        }
    }
    }
}
