import { Button, VerticalBox } from "std-widgets.slint";
import { LaunchStatus, GameInformation, GameInformationStatus } from "./datatypes.slint";
import { GameTab } from "./gametab.slint";
import { ErrorWindow } from "./errorwindow.slint";



export component AppWindow inherits Window {
    title: "Remote Play Non Steam Games";
    icon: @image_url("../assets/icon.png");
    default-font_size: 24px;

    preferred-height: 600px;
    preferred-width: 600px;

    in property <[GameInformation]> game_infos;

    callback launch_game(int) -> LaunchStatus;
    callback open_error_window();

    callback test_function() -> string;
    callback test_struct_function() -> LaunchStatus;

    VerticalLayout {
    
    
    test_label := Text {
        text: "sigma";
    }


    Button {
        property <bool> real: false;

        text: "Example button";
        clicked => {
            if real {
                test_label.text = "im at the claub";
            } else {
                test_label.text = root.test_function();
            }
            real = !real;
        }
    }

    Button {
        text: "Launch status";
        clicked => {
            let x = test_struct_function();
            if x.success {
                self.text = "sucessfully launched";
            } else {
                self.text = "Error: " + x.error;
            }
        }
    }

    in-out property <GameInformation> test_game: {
        display_name: "sigma",
        path: "skibidi",
        args: []
    };

    

    for g[i] in game_infos : GameTab {
        index: i;
        game_info: g;
        launch_game => launch_game(i);
    }
    }
}
