import { GameInformation, LaunchStatus } from "datatypes.slint";
import { Button } from "std-widgets.slint";



export component GameTab inherits Rectangle {
    in property <int> index;
    in property <GameInformation> game_info;
    callback launch_game(int);
    preferred-width: 600px;
    preferred-height: 300px;
    min-width: 400px;
    // background: #ffffff;
    
    HorizontalLayout {
        Rectangle {
            background: blue;
            width: 70%;
            Text {
                width: 100%;
                height: 100%;
                horizontal-alignment: left;
                overflow: elide;
                text: index + ". " + game_info.display_name;
            }
        }

        Button {
            width: 30%;
            height: 100%;
            text: "Launch";
            clicked => {
                // todo: error handling when a game launch fails
                launch_game(index);
            };
        }
    }
}
