# Great how toml natively supports comments
# remember to name as games.toml
[[game]]
path = 'C:\tools\Dolphin\Dolphin.exe'
arguments = ['-b', '-e', 'D:\Games\New Super Mario Bros. Wii (USA) (En,Fr,Es) (Rev 2).wbfs']
name = 'New super mario bros wii'

# also please avoid using tilde expansion (~)
[[game]]
path = 'C:\tools\Dolphin\Dolphin.exe'
arguments = ['-b', '-e', 'D:\Games\Legend of Zelda, The - Twilight Princess (Europe, Australia) (En,Fr,De,Es,It).wbfs']
name = 'Legend of Zelda - Twilight Princess'

[[game]]
path = 'C:\path\to\executable.exe'
name = 'Custom Game Name'
